apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: construction-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: Admin123
  REDIS_PASSWORD: RedisPass123
  Secret_Key: your-super-secret-jwt-token-key-change-in-production